#!/usr/bin/env python
"""Write and optionally run a repeatable Monata README demo."""

import argparse
import os
import subprocess
import sys
from pathlib import Path


DEMO_FILENAME = "monata_readme_demo.py"


DEMO_SOURCE = r'''#!/usr/bin/env python
"""Runnable Monata README demo generated by monata-sim-env."""

from pathlib import Path
import os
import shutil

from monata import LibraryRegistry
from monata.netlist import Circuit
from monata.sim.core import DCSpec, LocalExecutor, SimTask
from monata.techlib.registry import TechlibRegistry


def discover_techlibs():
    registry = TechlibRegistry()
    names = registry.list_techlibs()
    if names:
        return names

    monata_home = os.environ.get("MONATA_HOME")
    if monata_home:
        explicit = Path(monata_home).expanduser() / "techlibs"
        registry = TechlibRegistry(search_paths=[explicit], auto_discover=False)
        return registry.list_techlibs()
    return names


def main():
    demo_root = Path("monata_readme_demo_work")
    if demo_root.exists():
        shutil.rmtree(demo_root)
    demo_root.mkdir(parents=True)

    registry = LibraryRegistry()
    library = registry.create_library(path=demo_root / "analog", name="analog")
    cell = library.create_cell("rc_filter", description="RC low-pass filter")

    circuit = Circuit("rc low-pass")
    circuit.voltage("in", "vin", "0", "1")
    circuit.resistor("load", "vin", "vout", "1k")
    circuit.capacitor("hold", "vout", "0", "1n")

    print("cell:", cell.name)
    print("netlist:")
    print(circuit.to_spice())

    techlibs = discover_techlibs()
    print("techlibs:", ", ".join(techlibs) if techlibs else "(none)")
    expected = {"PTM_BULK", "PTM_MG"}
    if not expected.issubset(set(techlibs)):
        raise RuntimeError("expected PTM_BULK and PTM_MG in Monata techlib discovery")

    task = SimTask(
        circuit=circuit,
        analysis_spec=DCSpec(source="Vin", start=0, stop=1, step=0.25),
        output_names=["vout"],
    )

    result = LocalExecutor(max_workers=1).submit(task).result()
    if result.status != "ok":
        raise RuntimeError(result.error_message or "simulation failed")

    print("simulation:", result.status)
    print("sweep:", result.sweep_var.tolist() if result.sweep_var is not None else None)
    print("vout:", result.waveforms["vout"].tolist())


if __name__ == "__main__":
    main()
'''


def expand_path(value):
    return Path(value).expanduser().resolve()


def run(command, cwd, env):
    print("+ " + " ".join(str(part) for part in command), flush=True)
    subprocess.run([str(part) for part in command], cwd=str(cwd), env=env, check=True)


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-dir", default=".", help="Directory where the demo file should be written.")
    parser.add_argument("--monata-home", help="Monata home directory to export while running the demo.")
    parser.add_argument("--filename", default=DEMO_FILENAME, help="Demo filename.")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing demo file.")
    parser.add_argument("--run", action="store_true", help="Run the generated demo after writing it.")
    return parser.parse_args()


def main():
    args = parse_args()
    project_dir = expand_path(args.project_dir)
    target = project_dir / args.filename
    project_dir.mkdir(parents=True, exist_ok=True)
    if target.exists() and not args.force:
        raise SystemExit("demo file already exists: {}; rerun with --force to replace".format(target))
    target.write_text(DEMO_SOURCE, encoding="utf-8")
    print("Wrote Monata README demo: {}".format(target))

    if args.run:
        env = os.environ.copy()
        if args.monata_home:
            env["MONATA_HOME"] = str(expand_path(args.monata_home))
        run([sys.executable, target.name], project_dir, env)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
